name: proviante_notes

description: A Flutter Proviante notes

version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  isar_generator: ^3.0.5


flutter:
  uses-material-design: true